In [2]:
angka = [1, 2, 3, 4]
print(angka)

[1, 2, 3, 4]


In [5]:
import numpy as np
angka = np.array([1, 2, 3, 4])
print(angka)

[1 2 3 4]


In [6]:
import numpy as py

arr = np.array([10, 20, 30, 40])
print(arr)


[10 20 30 40]


In [11]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [12]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]])

print(arr.shape)

(2, 3)


In [13]:
print(arr.size)

6


In [14]:
print(arr.ndim)

2


In [16]:
a = np.array([1,2,3])
b = np.array([4,5,6])
total = a + b

print(total)

[5 7 9]


In [20]:
nilai = np.array([70,80,90])
total = nilai + 10
print(total)

[ 80  90 100]


In [18]:
print(total)

[5 7 9]


In [21]:
nilai = np.array([70,80,90])
total = nilai + 10
print(total)

[ 80  90 100]


In [22]:
nilai = np.array([70,80,90])
total = nilai *2
print(total)

[140 160 180]


In [29]:
nilai = np.array([70,80,90,85,95])
Rata_rata = np.mean(nilai)
Max = np.max(nilai)
Min = np.min(nilai)
Sum = np.sum(nilai)
print(Sum)
print(Min)
print(Max)
print(Rata_rata)

420
70
95
84.0


In [39]:
nilai = np.array([67,68,70,65,90,97,77,45,75])
kkm = 70

nilai_terbesar_ke2 = list(set(nilai))
nilai_terbesar_ke2.sort(reverse=True)

print(nilai_terbesar_ke2[])
tidak_lulus = np.sum(nilai<kkm)
lulus = np.sum(nilai>=kkm)
print(lulus)
print(tidak_lulus)

75
5
4


In [49]:
nilai = np.array([54,54,62,71,84])


duplicate=[]
for x in nilai:
    if x not in nilai:
      duplicate.append(x)

print(duplicate)

[]


In [59]:
nilai = np.array([67,68,70,65,90,97,77,45,75,78,88,74,60])

kkm=73

print(nilai.shape)
print(nilai.size)
print(nilai.ndim)

total = nilai*8
print(total)
tidak_lulus = np.sum(nilai<kkm)
print(tidak_lulus)

Rata_rata = np.mean(nilai)
print(Rata_rata)


Max = np.max(nilai)
print(Max)

Min = np.min(nilai)
print(Min)

(13,)
13
1
[536 544 560 520 720 776 616 360 600 624 704 592 480]
6
73.38461538461539
97
45
